# Generated by Django 5.0.2 on 2024-03-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='author',
            new_name='author_id',
        ),
    ]
