# Generated by Django 5.0.2 on 2024-03-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headsandtailsmodel',
            name='side',
            field=models.CharField(default='tails', max_length=10),
        ),
    ]
